[build]
  command = "npm install && npm run typecheck && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

# Variables de desarrollo
[context.branch-deploy]
  command = "npm run build"

[context.branch-deploy.environment]
  NODE_ENV = "development"
